### ISSUE TITLE
Requesting documentation

### ISSUE THREAD

**Issue by afkvido** [jasineri/idea-live-templates#1]
Hi! Please add documentation (ex. how to add this to your project), thanks!

**Comment by Domingosws** [comment]
Sim eu vou passar a adicionar documentação, obrigado pela dica!
Eu deixo  as minhas anotações mais importantes no caderno.
agora em diante eu vou passar á anotar !!!

**Comment by afkvido** [comment]
Thank you!

**Comment by jasineri** [comment]
Done :)

**Comment by afkvido** [comment]
Thank you very much!
